### ISSUE TITLE
IOError on Linux/Unix when setting stylesheet path

### ISSUE THREAD

**Issue by glutanimate** [upday7/TomatoClock#1]
First of all: This looks really cool! Kudos on the idea!

Just wanted to report a small issue when trying to run the add-on on Linux (I guess macOS will likely have the same problem:

```
  File "/home/glutanimate/AnkiTests/addons/TomatoClock/TomatoClock.py", line 47, in _set_style_sheet
    with open(os.path.join(os.path.dirname(__file__), "ui\designer\style.css"), "r") as f:
IOError: [Errno 2] No such file or directory: '/home/glutanimate/AnkiTests/addons/TomatoClock/ui\\designer\\style.css'
```

It's probably because of the backslashes in the path definition.

**Comment by upday7** [comment]
I just have fixed this issue because the wrong package was submitted to anki web .. that file should not be missing ...

**Comment by upday7** [comment]
@glutanimate fixed already : D

**Comment by glutanimate** [comment]
Thanks! I can confirm that the error is gone.
