### ISSUE TITLE
Conflicts with "More overview Stats 2"

### ISSUE THREAD

**Issue by FluorineTinOxide** [upday7/TomatoClock#7]
Tomato clock is an amazing addon, possible my new favorite. Only biggest issues are that it conflicts with "More Overview Stats 2" and Night mode which. If the "More overview stats 2" stats could be integrated into the addon that would be great, thank you!

**Comment by upday7** [comment]
Hello, good to hear from you,  its not possible to use both More overview stats 2 and tomato clock .. as which changed the Overview part ... and can only exists one at a time ...
